### ISSUE TITLE
React group project: set up your Kanban board

### ISSUE THREAD

**Issue by MarcoOquendoC** [MarcoOquendoC/space-travelers#25]
# [React group project: set up your Kanban board](https://github.com/microverseinc/curriculum-react-redux/blob/main/group-project/setup_kanban_board.md)

## Hi good reviewer,

![Patricio greeting](https://media.giphy.com/media/3ogwFGEHrVxusDbDjO/giphy.gif)

### Project requirements

- [link to the project](https://github.com/MarcoOquendoC/space-travelers/).
- There are three people in our team.

**Comment by mikethreels** [comment]
Hi team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- great job following the instructions.
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
